# Generated by Django 4.2.2 on 2023-06-18 01:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('codfilial', models.AutoField(primary_key=True, serialize=False)),
                ('dtinclusao', models.DateField()),
                ('dtencerramento', models.DateField(blank=True, null=True)),
                ('cnpj', models.CharField(max_length=14)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'filial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('codlocal', models.AutoField(primary_key=True, serialize=False)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'localidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metafilial',
            fields=[
                ('nivelfilial', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('vigencia', models.CharField(max_length=6)),
                ('bonvendedor', models.FloatField()),
                ('bongerente', models.FloatField()),
            ],
            options={
                'db_table': 'metafilial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nivelfilial',
            fields=[
                ('nivelfilial', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'nivelfilial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nivelvendedor',
            fields=[
                ('nivelvendedor', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'nivelvendedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('login', models.CharField(max_length=256)),
                ('senha', models.CharField(max_length=256)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo')])),
                ('dtinclusao', models.DateField(default=datetime.datetime.now)),
                ('dtencerramento', models.DateField(blank=True, null=True)),
                ('tipo', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Gerente'), (3, 'Vendedor')])),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('codvendedor', models.IntegerField(primary_key=True, serialize=False)),
                ('datavenda', models.DateField()),
                ('valorfaturado', models.FloatField()),
            ],
            options={
                'db_table': 'venda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metavendedor',
            fields=[
                ('nivelvendedor', models.OneToOneField(db_column='nivelvendedor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.nivelvendedor')),
                ('vigencia', models.CharField(max_length=6)),
                ('pctgmeta', models.FloatField()),
                ('bonificacao', models.FloatField()),
            ],
            options={
                'db_table': 'metavendedor',
                'managed': False,
            },
        ),
    ]
